### PR TITLE
add nbdev flags to test action

### PR DESCRIPTION
**Pull request by filipj8**

### CODE REVIEW

**Comment by jph00** [comment]
Thanks for the PR. FYI it's a good idea to at-mention me so I get notified.

**Comment by jph00** [comment]
I had to revert this because it's missing a default.

**Comment by filipj8** [comment]
@jph00 it looks like the [4f7b3fc](https://github.com/fastai/workflows/pull/56/commits/4f7b3fcba203d6fe647bd2a35cd7a3bd2634f9c6) merged caused issues with the default. I'll put up another PR

**Comment by jph00** [comment]
Oh sorry did I mess up the merge? Oops!

**Pull request merged**
