### PR TITLE
Add delete flag to rsync 

### PR DESCRIPTION
**Pull request by hamelsmu**
See https://github.com/fastai/fastcore/issues/178

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 ready for review

**Comment by jph00** [comment]
I'd suggest making this optional with an arg that defaults to False. `--delete` is really dangerous, because if you are accidentally pointing at the wrong directory, then it will literally delete all the files in that directory!

**Comment by hamelsmu** [comment]
@jph00 what about this?

**Comment by jph00** [comment]
Works - but pretty ugly! ;) Try this
image

**Comment by hamelsmu** [comment]
Wow what is this magic

**Comment by jph00** [comment]
https://tldp.org/LDP/abs/html/parameter-substitution.html
:)

**Comment by hamelsmu** [comment]
thanks for showing me

**Pull request merged**
